# Name of your site (displayed in the header)
name: Andrew Tarry

# Short bio or description (displayed in the header)
description: Software Engineer, Architect, DevOps Engineer and Technologist (from London)
url: "https://andrewtarry.com"

baseurl: /
permalink: /:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
