# Name of your site (displayed in the header)
name: Andrew Tarry

# Short bio or description (displayed in the header)
description: Web Developer from London

baseurl: /
permalink: /:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
