#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Andrew Tarry

# Short bio or description (displayed in the header)
description: Web Developer from London

baseurl: /
markdown: kramdown
#highlighter: pygments
permalink: /:title/

gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
